symandy_makefile_maker:
  executables:
    - { name: composer }
    - { name: symfony_bin, filename: symfony }
    - { name: symfony_console, filename: symfony, output: console }
    - { name: yarn }

  groups:
    composer:
      commands:
        install:
          name: composer-install
          description: Install composer dependencies
          instructions:
            - { executable: composer, name: install }

        update:
          name: composer-update
          description: Update composer dependencies
          instructions:
            - { executable: composer, name: update }

        validate:
          name: composer-validate
          description: Validate composer.json and composer.lock
          instructions:
            - { executable: composer, name: validate }

        dump:
          name: composer-dump
          description: Dump composer autoload
          instructions:
            - { executable: composer, name: dump-autoload }

        dump_prod:
          name: composer-dump-prod
          description: Dump composer autoload for prod environment
          instructions:
            - executable: composer
              name: dump-autoload
              options:
                - { key: no-dev }
                - { key: classmap-authoritative }
                - { key: optimize }

    doctrine:
      commands:
        db_cache:
          name: db-cache
          description: Clear doctrine database cache
          instructions:
            - { executable: symfony_console, name: doctrine:cache:clear-metadata }
            - { executable: symfony_console, name: doctrine:cache:clear-query }
            - { executable: symfony_console, name: doctrine:cache:clear-result }

        db_create:
          name: db-create
          description: Create database and schema
          instructions:
            - executable: symfony_console
              name: doctrine:database:create
              options:
                - { key: if-not-exists }
            - { executable: symfony_console, name: doctrine:schema:create }

        db_diff:
          name: db-diff
          description: List SQL requests to update database
          instructions:
            - executable: symfony_console
              name: doctrine:schema:update
              options:
                - { key: dump-sql }

        db_migrate:
          name: db-migrate
          description: Execute not executed migrations
          instructions:
            - { executable: symfony_console, name: doctrine:migrations:migrate }

        db_migrate_diff:
          name: db-migrate-diff
          description: Generate new migration with diff SQL queries
          instructions:
            - { executable: symfony_console, name: doctrine:migrations:diff }

        db_migrate_list:
          name: db-migrate-list
          description: List not executed migrations
          instructions:
            - { executable: symfony_console, name: doctrine:migrations:list }

        db_migrate_status:
          name: db-migrate-status
          description: Display migration versions status
          instructions:
            - { executable: symfony_console, name: doctrine:migrations:status }

        db_update:
          name: db-update
          description: Update database to latest mapping
          instructions:
            - executable: symfony_console
              name: doctrine:schema:update
              options:
                - { key: force }

        db_validate:
          name: db-validate
          description: Validate entities and database sync with mapping
          instructions:
            - { executable: symfony_console, name: doctrine:schema:validate }

    messenger:
      commands:
        messenger_start:
          name: messenger-start
          description: Consume messenger messages
          instructions:
            - { executable: symfony_console, name: messenger:consume }

        messenger_loud:
          name: messenger-loud
          description: Consume messenger messages with -vv flag
          instructions:
            - executable: symfony_console
              name: messenger:consume
              options:
                - { key: -vv }

        messenger_stop:
          name: messenger-stop
          description: Stop messenger workers after current message
          instructions:
            - { executable: symfony_console, name: messenger:stop-workers }

    symfony:
      commands:
        requirements:
          name: requirements
          description: Check Symfony requirements
          instructions:
            - { executable: symfony_bin, name: check:requirements }

        security:
          name: security
          description: Check packages vulnerabilities (using composer.lock)
          instructions:
            - { executable: symfony_bin, name: check:security }

        serve:
          name: serve
          description: Run symfony web server in the background
          instructions:
            - executable: symfony_bin
              name: serve
              options:
                - { key: daemon }

        server-stop:
          name: server-stop
          description: Stop symfony web server
          instructions:
            - { executable: symfony_bin, name: server:stop }

    lint:
      commands:
        lint-container:
          name: lint-container
          description: Ensure that arguments injected into services match type declarations
          instructions:
            - { executable: symfony, name: lint:container }

        lint-twig-prod:
          name: lint-twig-prod
          description: Check twig syntax in /templates folder (prod environment)
          instructions:
            - executable: symfony
              name: lint:twig
              arguments: [templates]
              options:
                - { key: e, value: prod}

        lint-xliff:
          name: lint-xliff
          description: Check xliff syntax in /translations folder
          instructions:
            - executable: symfony
              name: lint:xliff
              arguments: [translations]

        lint-yaml:
          name: lint-yaml
          description: Check yaml syntax in /config and /translations folders
          instructions:
            - executable: symfony
              name: lint-yaml
              arguments: [config, translations]
